// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// parse_binary
IntegerVector parse_binary(CharacterVector s);
RcppExport SEXP _utf8splain_parse_binary(SEXP sSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type s(sSEXP);
    rcpp_result_gen = Rcpp::wrap(parse_binary(s));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_utf8splain_parse_binary", (DL_FUNC) &_utf8splain_parse_binary, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_utf8splain(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
