# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

parse_binary <- function(s) {
    .Call('_utf8splain_parse_binary', PACKAGE = 'utf8splain', s)
}

